name: End User Testing Bug Reporting Template
description: Template to report bugs for each program during end user testing
title: End User Testing Bug Report
labels: bug
assignees: tartenouveau
body:
- type: textarea
  attributes:
    label: Scenario Details
    description: Provide the scenario issue number and scenario from the testing workbook
    placeholder: 1b, Enter impact percentage for the team
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: What happened?
    placeholder: Octobot couldnt find the answer
  validations:
    required: true
- type: textarea
  attributes:
    label: Query
    description: Provide the exact query (question) you used. 
    placeholder: eg: How much PTO do we get in the UK?
  validations:
    required: True
- type: textarea
  attributes:
    label: Expected Response
    description: What answer did you expect to receive? 
    placeholder: Provide a link to the article in Zendesk with the answer included. 
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Response
    description: How did Octobot Respond?
    placeholder: Provide a screenshot of the response and links to any documentation Octobot referenced. 
  validations:
    required: true
