name: End User Testing Bug Reporting Template
description: Template to report bugs for each program during end user testing
title: End User Testing Bug Report
labels: bug
assignees: tartenouveau
body:
- type: textarea
  attributes:
    label: Scenario Details
    placeholder: link the scenario issue here
  validations:
    required: true
- type: textarea
  attributes:
    label: Result
    placeholder: Wrong answer, no answer
  validations:
    required: true
- type: textarea
  attributes:
    label: Query
    placeholder: Provide the exact query you used. 
  validations:
    required: True
- type: textarea
  attributes:
    label: Expected Response
    placeholder: What answer did you expect to receive? Link the article in Zendesk where the answer can be found. 
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Response
    placeholder: Provide a screenshot of the response and links to any documentation Octobot referenced. 
  validations:
    required: true
