name: Octobot Testing Scenario Template
description: Issue template for tracking test queries.
title: ITEM NUMBER | SCENARIO NAME
labels: scenario
body:
- type: textarea
  attributes:
    label: Query
    placeholder: Provide the exact query you asked OctoBot.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Response
    placeholder: What answer did you expect to receive? Link the article in Zendesk where the answer can be found. 
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Response
    placeholder: Provide a screenshot of the response and links to any documentation Octobot referenced. 
  validations:
    required: true
- type: textarea
  attributes:
    label: Comments
    placeholder: Anything else to share?
  validations:
    required: False
