name: Octobot Testing Scenario Template
description: Issue template for tracking test queries.
title: ITEM NUMBER | SCENARIO NAME
labels: scenario
body:
- type: input
  attributes:
    label: Query
    description: Provide the exact query you asked OctoBot.
    placeholder: How much PTO do we get in the UK?
  validations:
    required: true
- type: dropdown
  id: pass or fail
  attributes:
    label: Pass or Fail?
    description: If the response failed, please open a bug ticket to track the error for follow up. 
    options: 
    - Pass
    - Fail
  validations:
    required: true
- type: textarea
  attributes:
    label: Response
    description: How did OctoBot respond to the Query
    placeholder: Provide a screenshot of OctoBots response and links to the Zendesk articles referenced
  validations:
    required: true
- type: textarea
  attributes:
    label: Comments
    description: Anything else to share?
    placeholder: 
  validations:
    required: False
