name: End User Testing Scenario Template
description: Template to create scenarios for each program during end user testing
title: SCENARIO NAME
labels: scenario
assignees: devonliana
body:
- type: input
  attributes:
    label: Test type
    description: Provide the type of test
    placeholder: Functionality testing
  validations:
    required: true
- type: input
  attributes:
    label: User type
    description: Provide the type of user for testing
    placeholder: HRPB
  validations:
    required: true
- type: input
  attributes:
    label: Test As
    description: Provide user to proxy as, or enter Test as Self
  validations:
    required: true
- type: textarea
  attributes:
    label: Acceptance Criteria
    description: Describe what needs to happen for the test to be considered successful
    placeholder: Employee successfully views inbox task
  validations:
    required: True
- type: textarea
  attributes:
    label: Test Steps
    description: Outline necessary steps when to proxy, reports to check, tasks to complete to ensure configuration is working as intended
    placeholder: Confirm details of inbox task, click submit and check report to see that the action is complete 
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Result
    description: What should happen?
    placeholder: Inbox task should exist, should be able to submit, and report should list employee as completed. 
  validations:
    required: true
